from typing import List, Tuple

class LockFileWriter:
    def write(self, file_path: str, pinned_data: List[Tuple[str, str, List[str]]]):
        """
        pinned_data: List of (name, version, hashes)
        """
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write("# Generated by req-pinner\n")
            f.write("# This file contains pinned versions and hashes for security.\n\n")
            
            for name, version, hashes in pinned_data:
                f.write(f"{name}=={version} \\\n")
                for h in hashes:
                    f.write(f"    --hash=sha256:{h} \\\n")
                f.write("\n")
        print(f"[Success] Lock file created at: {file_path}")